import os


WEATHER_VARIABLES = {
    "refc": {
        "nomads_params": ["var_REFC"],
        "level_params": [],
        "display_name": "Radar Reflectivity",
        "units": "dBZ",
        "short_name": "refc",
        "colormap": "nws_reflectivity",
        "vmin": 5,
        "vmax": 75,
        "category": "precipitation",
    },
    "asnow": {
        "nomads_params": ["var_ASNOW"],
        "level_params": [],
        "display_name": "Accumulated Snowfall",
        "units": "in",
        "short_name": "asnow",
        "colormap": "snow_accumulation",
        "vmin": 0,
        "vmax": 24,
        "category": "winter",
        "conversion": "kg_m2_to_in",
        "is_accumulation": True,
    },
    "snod": {
        "nomads_params": ["var_SNOD"],
        "level_params": [],
        "display_name": "Snow Depth",
        "units": "in",
        "short_name": "snod",
        "colormap": "snow_depth",
        "vmin": 0,
        "vmax": 36,
        "category": "winter",
        "conversion": "m_to_in",
    },
    "apcp": {
        "nomads_params": ["var_APCP"],
        "level_params": [],
        "display_name": "Accumulated Precipitation",
        "units": "in",
        "short_name": "apcp",
        "colormap": "precip_accumulation",
        "vmin": 0,
        "vmax": 6,
        "category": "precipitation",
        "conversion": "kg_m2_to_in",
        "is_accumulation": True,
    },
    "prate": {
        "nomads_params": ["var_PRATE"],
        "level_params": [],
        "display_name": "Precipitation Rate",
        "units": "in/hr",
        "short_name": "prate",
        "colormap": "precip_rate",
        "vmin": 0,
        "vmax": 2,
        "category": "precipitation",
        "conversion": "kg_m2_s_to_in_hr",
    },
    "t2m": {
        "nomads_params": ["var_TMP"],
        "level_params": ["lev_2_m_above_ground=on"],
        "display_name": "2m Temperature",
        "units": "°F",
        "short_name": "t2m",
        "colormap": "temperature",
        "vmin": -40,
        "vmax": 110,
        "category": "temperature",
        "conversion": "k_to_f",
        "source_short_names": ["t2m", "2t", "tmp"],
    },
    "dpt": {
        "nomads_params": ["var_DPT"],
        "level_params": ["lev_2_m_above_ground=on"],
        "display_name": "2m Dew Point",
        "units": "°F",
        "short_name": "dpt",
        "colormap": "temperature",
        "vmin": -40,
        "vmax": 80,
        "category": "temperature",
        "conversion": "k_to_f",
        "source_short_names": ["dpt", "2d"],
    },
    "rh": {
        "nomads_params": ["var_RH"],
        "level_params": ["lev_2_m_above_ground=on"],
        "display_name": "Relative Humidity",
        "units": "%",
        "short_name": "rh",
        "colormap": "humidity",
        "vmin": 0,
        "vmax": 100,
        "category": "temperature",
    },
    "wind_10m": {
        "nomads_params": ["var_UGRD", "var_VGRD"],
        "level_params": ["lev_10_m_above_ground=on"],
        "display_name": "10m Wind Speed",
        "units": "mph",
        "short_name": "wind_10m",
        "colormap": "wind",
        "vmin": 0,
        "vmax": 80,
        "category": "wind",
        "conversion": "m_s_to_mph",
        "vector_components": ["ugrd", "vgrd"],
    },
    "gust": {
        "nomads_params": ["var_GUST"],
        "level_params": ["lev_10_m_above_ground=on"],
        "display_name": "Wind Gusts",
        "units": "mph",
        "short_name": "gust",
        "colormap": "wind",
        "vmin": 0,
        "vmax": 90,
        "category": "wind",
        "conversion": "m_s_to_mph",
    },
    "cape": {
        "nomads_params": ["var_CAPE"],
        "level_params": ["lev_surface=on"],
        "display_name": "CAPE",
        "units": "J/kg",
        "short_name": "cape",
        "colormap": "severe",
        "vmin": 0,
        "vmax": 4000,
        "category": "severe",
    },
    "hlcy": {
        "nomads_params": ["var_HLCY"],
        "level_params": ["lev_0-3_km_above_ground=on"],
        "display_name": "Storm Relative Helicity",
        "units": "m²/s²",
        "short_name": "hlcy",
        "colormap": "severe",
        "vmin": 0,
        "vmax": 600,
        "category": "severe",
    },
    "hail": {
        "nomads_params": ["var_HAIL"],
        "level_params": [],
        "display_name": "Hail",
        "units": "in",
        "short_name": "hail",
        "colormap": "severe",
        "vmin": 0,
        "vmax": 3,
        "category": "severe",
    },
    "vis": {
        "nomads_params": ["var_VIS"],
        "level_params": ["lev_surface=on"],
        "display_name": "Visibility",
        "units": "mi",
        "short_name": "vis",
        "colormap": "visibility",
        "vmin": 0,
        "vmax": 10,
        "category": "surface",
        "conversion": "m_to_mi",
    },
}

WEATHER_CATEGORIES = {
    "precipitation": "Precipitation & Storms",
    "winter": "Winter Weather",
    "wind": "Wind",
    "temperature": "Temperature & Moisture",
    "severe": "Severe Weather",
    "surface": "Surface",
}

MODELS = {
    "hrrr": {
        "name": "HRRR",
        "max_forecast_hours": 24,
        "update_frequency_hours": 1,
        "nomads_url": "https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_2d.pl",
        "dir_pattern": "%2Fhrrr.{date_str}%2Fconus",
        "file_pattern": "hrrr.t{init_hour}z.wrfsfcf{forecast_hour}.grib2",
        "availability_check_var": "var_REFC",
    },
    "nam_nest": {
        "name": "NAM 3km CONUS",
        "max_forecast_hours": 60,
        "update_frequency_hours": 6,
        "nomads_url": "https://nomads.ncep.noaa.gov/cgi-bin/filter_nam_conusnest.pl",
        "dir_pattern": "%2Fnam.{date_str}",
        "file_pattern": "nam.t{init_hour}z.conusnest.hiresf{forecast_hour}.tm00.grib2",
        "availability_check_var": "var_REFC",
    },
    "nam_12km": {
        "name": "NAM 12km",
        "max_forecast_hours": 84,
        "update_frequency_hours": 6,
        "nomads_url": "https://nomads.ncep.noaa.gov/cgi-bin/filter_nam.pl",
        "dir_pattern": "%2Fnam.{date_str}",
        "file_pattern": "nam.t{init_hour}z.awphys{forecast_hour}.tm00.grib2",
        "availability_check_var": "var_REFC",
    },
}

repomap = {
    "CACHE_DIR": "cache",
    "DEFAULT_MODEL": "hrrr",
    "DEFAULT_VARIABLE": "refc",
    "WEATHER_VARIABLES": WEATHER_VARIABLES,
    "WEATHER_CATEGORIES": WEATHER_CATEGORIES,
    "MODELS": MODELS,
    "COUNTY_ZIP_NAME": "cb_2018_us_county_20m.zip",
    "COUNTY_DIR_NAME": "county_shapefile",
    "COUNTY_SHP_NAME": "cb_2018_us_county_20m.shp",
    "MAX_RUNS_TO_KEEP": 24,  # Number of model runs to keep in cache (24 = last 24 hours)

    # Location configurations
    "LOCATIONS": {
        "philly": {
            "name": "Philadelphia",
            "center_lat": 40.04877,
            "center_lon": -75.38903,
            "zoom": 1.5,
            "lat_min": 38.8,
            "lat_max": 40.7,
            "lon_min": -76.5,
            "lon_max": -73.5,
        },
        "nyc": {
            "name": "New York City",
            "center_lat": 40.7128,
            "center_lon": -74.0060,
            "zoom": 1.5,
            "lat_min": 39.5,
            "lat_max": 41.5,
            "lon_min": -75.0,
            "lon_max": -72.0,
        },
    },
}

if not os.path.exists(repomap["CACHE_DIR"]):
    os.makedirs(repomap["CACHE_DIR"])
