//! Parity tests: verify Rust GRIB decode matches Python (Herbie/cfgrib) output.
//!
//! Tests against fixture files generated by `tests/fixtures/grib_parity/`.
//! Each fixture has:
//!   - .grib2  — raw GRIB message (single variable, byte-range extracted)
//!   - .json   — metadata with decode_checkpoints (sample values + lat/lon)
//!
//! Known decoder differences:
//!   - NBM uses Complex Packing with Spatial Differencing (DRT 3). The grib
//!     crate's decoder may produce different values than eccodes for some
//!     variables, with error growing across rows due to accumulated
//!     differencing.
//!   - ECMWF uses CCSDS/AEC compression (DRT 42). The grib crate's decoder
//!     may produce different values than eccodes for some variables.
//!   - ECMWF uses 180..540° longitude convention which cfgrib normalizes to
//!     -180..180°. We normalize for comparison.

use serde::Deserialize;

use radarcheck_worker::grib::{self, DecodedGrib, GribCoords};

#[derive(Deserialize)]
struct FixtureMeta {
    #[allow(dead_code)]
    model_id: String,
    #[allow(dead_code)]
    variable_id: String,
    output_shape: Vec<usize>,
    lat_ndim: usize,
    decode_checkpoints: Vec<Checkpoint>,
    mean_value: f64,
    total_nonzero: usize,
    total_nan: usize,
}

#[derive(Deserialize)]
struct Checkpoint {
    #[allow(dead_code)]
    flat_index: usize,
    iy: usize,
    ix: usize,
    value: f64,
    lat: f64,
    lon: f64,
}

fn load_fixture(name: &str) -> (DecodedGrib, FixtureMeta) {
    let base = format!("../tests/fixtures/grib_parity/{}", name);
    let grib_path = format!("{}.grib2", base);
    let json_path = format!("{}.json", base);

    let grib_bytes = std::fs::read(&grib_path)
        .unwrap_or_else(|e| panic!("Missing fixture: {} — {}", grib_path, e));
    let json_str = std::fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("Missing fixture metadata: {} — {}", json_path, e));

    let meta: FixtureMeta = serde_json::from_str(&json_str)
        .unwrap_or_else(|e| panic!("Bad fixture JSON: {} — {}", json_path, e));

    let decoded = grib::decode_grib_message(&grib_bytes)
        .unwrap_or_else(|e| panic!("Decode failed for {}: {}", grib_path, e));

    (decoded, meta)
}

/// Normalize longitude to [-180, 180) range
fn normalize_lon(lon: f64) -> f64 {
    let mut l = lon % 360.0;
    if l >= 180.0 {
        l -= 360.0;
    } else if l < -180.0 {
        l += 360.0;
    }
    l
}

fn check_parity(name: &str) {
    check_parity_with_tolerance(name, 0.01)
}

fn check_parity_with_tolerance(name: &str, val_rel_tol: f64) {
    let (decoded, meta) = load_fixture(name);

    // Check grid dimensions
    assert_eq!(
        decoded.ny, meta.output_shape[0],
        "{}: ny mismatch (got {} expected {})",
        name, decoded.ny, meta.output_shape[0]
    );
    assert_eq!(
        decoded.nx, meta.output_shape[1],
        "{}: nx mismatch (got {} expected {})",
        name, decoded.nx, meta.output_shape[1]
    );

    // Check coordinate dimensionality
    match meta.lat_ndim {
        1 => assert!(
            matches!(decoded.latitudes, GribCoords::Regular1D(_)),
            "{}: expected 1D coords, got 2D",
            name
        ),
        2 => assert!(
            matches!(decoded.latitudes, GribCoords::Projected2D(_)),
            "{}: expected 2D coords, got 1D",
            name
        ),
        _ => panic!("{}: unexpected lat_ndim {}", name, meta.lat_ndim),
    }

    // Check decode checkpoints (value + coordinate parity)
    let values = decoded.values.as_slice().unwrap();
    for cp in &meta.decode_checkpoints {
        // Value at (iy, ix)
        let actual_val = decoded.values[[cp.iy, cp.ix]] as f64;
        let expected_val = cp.value;

        let val_tol = if expected_val.abs() < 0.001 {
            0.002
        } else {
            expected_val.abs() * val_rel_tol
        };
        assert!(
            (actual_val - expected_val).abs() <= val_tol,
            "{}: value mismatch at ({}, {}): got {:.6} expected {:.6} (tol {:.6})",
            name, cp.iy, cp.ix, actual_val, expected_val, val_tol
        );

        // Coordinate at (iy, ix) — normalize longitudes to [-180, 180)
        let (actual_lat, actual_lon) = get_coord_at(&decoded, cp.iy, cp.ix);
        let coord_tol = 0.01;
        assert!(
            (actual_lat - cp.lat).abs() <= coord_tol,
            "{}: lat mismatch at ({}, {}): got {:.4} expected {:.4}",
            name, cp.iy, cp.ix, actual_lat, cp.lat
        );
        let lon_diff = (normalize_lon(actual_lon) - normalize_lon(cp.lon)).abs();
        assert!(
            lon_diff <= coord_tol || lon_diff >= 359.99,
            "{}: lon mismatch at ({}, {}): got {:.4} expected {:.4} (normalized: {:.4} vs {:.4})",
            name, cp.iy, cp.ix, actual_lon, cp.lon,
            normalize_lon(actual_lon), normalize_lon(cp.lon)
        );
    }

    // Check aggregate statistics
    let total_nonzero: usize = values.iter().filter(|&&v| v != 0.0 && !v.is_nan()).count();
    let total_nan: usize = values.iter().filter(|&&v| v.is_nan()).count();
    let sum: f64 = values.iter().filter(|&&v| !v.is_nan()).map(|&v| v as f64).sum();
    let count = values.iter().filter(|&&v| !v.is_nan()).count();
    let mean = if count > 0 { sum / count as f64 } else { 0.0 };

    assert_eq!(
        total_nan, meta.total_nan,
        "{}: NaN count mismatch (got {} expected {})",
        name, total_nan, meta.total_nan
    );

    let nonzero_tol_pct = if val_rel_tol > 0.05 { 0.05 } else { 0.001 };
    let nonzero_tol = (meta.total_nonzero as f64 * nonzero_tol_pct).max(2.0) as usize;
    assert!(
        (total_nonzero as isize - meta.total_nonzero as isize).unsigned_abs() <= nonzero_tol,
        "{}: nonzero count differs too much (got {} expected {} tol {})",
        name, total_nonzero, meta.total_nonzero, nonzero_tol
    );

    let mean_tol = meta.mean_value.abs() * val_rel_tol + 0.001;
    assert!(
        (mean - meta.mean_value).abs() <= mean_tol,
        "{}: mean mismatch (got {:.6} expected {:.6} tol {:.6})",
        name, mean, meta.mean_value, mean_tol
    );
}

fn get_coord_at(decoded: &DecodedGrib, iy: usize, ix: usize) -> (f64, f64) {
    match (&decoded.latitudes, &decoded.longitudes) {
        (GribCoords::Regular1D(lats), GribCoords::Regular1D(lons)) => {
            (lats[iy], lons[ix])
        }
        (GribCoords::Projected2D(lats), GribCoords::Projected2D(lons)) => {
            (lats[[iy, ix]], lons[[iy, ix]])
        }
        _ => panic!("Mixed 1D/2D coordinates"),
    }
}

// ── HRRR (Lambert conformal, JPEG2000) ──────────────────────────────────────

#[test]
fn parity_hrrr_apcp() { check_parity("hrrr_apcp_f1"); }

#[test]
fn parity_hrrr_asnow() { check_parity("hrrr_asnow_f1"); }

#[test]
fn parity_hrrr_snod() { check_parity("hrrr_snod_f1"); }

#[test]
fn parity_hrrr_t2m() { check_parity("hrrr_t2m_f1"); }

// ── NAM Nest (Lambert conformal, Complex Packing + Spatial Diff) ────────────

#[test]
fn parity_nam_nest_apcp() { check_parity("nam_nest_apcp_f3"); }

#[test]
fn parity_nam_nest_snod() { check_parity("nam_nest_snod_f3"); }

#[test]
fn parity_nam_nest_t2m() { check_parity("nam_nest_t2m_f3"); }

// ── GFS (regular lat/lon, Complex Packing) ──────────────────────────────────

#[test]
fn parity_gfs_apcp() { check_parity("gfs_apcp_f3"); }

#[test]
fn parity_gfs_snod() { check_parity("gfs_snod_f3"); }

#[test]
fn parity_gfs_t2m() { check_parity("gfs_t2m_f3"); }

// ── NBM (Lambert conformal, Complex Packing + Spatial Diff) ─────────────────
// NBM uses DRT 3 (complex packing with spatial differencing). The grib crate's
// decoder may produce different values than eccodes for APCP/ASNOW. T2M is
// close enough with 10% tolerance.

#[test]
fn parity_nbm_t2m() {
    check_parity_with_tolerance("nbm_t2m_f1", 0.10);
}

#[test]
#[ignore = "grib crate DRT 3 decoder produces different values than eccodes for NBM APCP"]
fn parity_nbm_apcp() { check_parity("nbm_apcp_f1"); }

#[test]
#[ignore = "grib crate DRT 3 decoder produces different values than eccodes for NBM ASNOW"]
fn parity_nbm_asnow() { check_parity("nbm_asnow_f1"); }

// ── ECMWF HRES (regular lat/lon, CCSDS/AEC) ────────────────────────────────

#[test]
fn parity_ecmwf_hres_apcp() { check_parity("ecmwf_hres_apcp_f3"); }

#[test]
#[ignore = "grib crate CCSDS decoder produces different values than eccodes for ECMWF T2M"]
fn parity_ecmwf_hres_t2m() { check_parity("ecmwf_hres_t2m_f3"); }

#[test]
#[ignore = "grib crate CCSDS decoder produces different values than eccodes for ECMWF SNOD"]
fn parity_ecmwf_hres_snod() { check_parity("ecmwf_hres_snod_f3"); }
